apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-frontend
spec:
  replicas: 1  # HPA will manage this
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: mohdyousuf9059/portfolio-frontend:latest
        ports:
        - containerPort: 80
        # Resource requests and limits are REQUIRED for HPA
        resources:
          requests:
            cpu: 100m      # 0.1 CPU core
            memory: 128Mi  # 128 MB RAM
          limits:
            cpu: 500m      # 0.5 CPU core max
            memory: 512Mi  # 512 MB RAM max
        # Health checks for better reliability
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5