apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  labels:
    app: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: portfolio-frontend
  minReplicas: 1    # Minimum number of pods
  maxReplicas: 5    # Maximum number of pods
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Scale when CPU > 70%
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80  # Scale when Memory > 80%
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60      # Wait 1 min before scaling up
      policies:
      - type: Percent
        value: 50                         # Scale up by 50% of current replicas
        periodSeconds: 60
      - type: Pods
        value: 2                          # Or add max 2 pods
        periodSeconds: 60
      selectPolicy: Min                   # Use the smaller of the two policies
    scaleDown:
      stabilizationWindowSeconds: 300     # Wait 5 min before scaling down
      policies:
      - type: Percent
        value: 50                         # Scale down by 50% of current replicas
        periodSeconds: 60
      - type: Pods
        value: 1                          # Or remove max 1 pod
        periodSeconds: 60
      selectPolicy: Max   