apiVersion: v1
kind: Service
metadata:
  name: skooner-service
  namespace: skooner
  labels:
    app: skooner
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 4654
    nodePort: 30001
    protocol: TCP
    name: http
  selector:
    app: skooner
---
apiVersion: v1
kind: Service
metadata:
  name: skooner-loadbalancer
  namespace: skooner
  labels:
    app: skooner
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4654
    protocol: TCP
    name: http
  selector:
    app: skooner