apiVersion: v1
kind: Service
metadata:
  name: skooner-service
  namespace: skooner
  labels:
    app: skooner
spec:
  type: NodePort
  ports:
  - port: 4654
    targetPort: 4654
    nodePort: 30123
    protocol: TCP
    name: http
  selector:
    app: skooner
---
apiVersion: v1
kind: Service
metadata:
  name: skooner-clusterip
  namespace: skooner
  labels:
    app: skooner
spec:
  type: ClusterIP
  ports:
  - port: 4654
    targetPort: 4654
    protocol: TCP
    name: http
  selector:
    app: skooner
