apiVersion: v1
kind: Namespace
metadata:
  name: skooner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skooner-sa
  namespace: skooner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: skooner-sa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: skooner-sa
  namespace: skooner
---
apiVersion: v1
kind: Secret
metadata:
  name: skooner-sa-token
  namespace: skooner
  annotations:
    kubernetes.io/service-account.name: skooner-sa
type: kubernetes.io/service-account-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skooner
  namespace: skooner
  labels:
    app: skooner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skooner
  template:
    metadata:
      labels:
        app: skooner
    spec:
      serviceAccountName: skooner-sa
      containers:
      - name: skooner
        image: ghcr.io/skooner-k8s/skooner:stable
        ports:
        - containerPort: 4654
          name: http
          protocol: TCP
        env:
         - name: AUTH_TOKEN
           valueFrom:
             secretKeyRef:
               name: skooner-token
               key: token
         - name: METRICS_PROVIDER
           value: "prometheus"
         - name: METRICS_PROMETHEUS_URL
           value: "http://prometheus-service.monitoring:9090"
         - name: KUBERNETES_NAMESPACE
           valueFrom:
             fieldRef:
               fieldPath: metadata.namespace
         - name: SERVER_ROOT
           value: "/"
        args:
        - --insecure-port=4654
        - --enable-insecure-login
        - --system-banner="Portfolio Monitoring Dashboard"
        livenessProbe:
          httpGet:
            path: /
            port: 4654
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 4654
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
